# Generated by Django 5.0.3 on 2024-05-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.IntegerField(default=1),
        ),
    ]
