# Generated by Django 5.0.3 on 2024-05-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_skill_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('boxicons', models.TextField(default='<i class="bx bx-code-block"></i>')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='title_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='title_description_1',
            field=models.TextField(max_length=500),
        ),
    ]
