# Generated by Django 5.0.3 on 2024-05-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_education_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
