# Generated by Django 5.0.3 on 2024-05-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_education_id_alter_resume_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='university_link',
            field=models.URLField(),
        ),
    ]
