# Generated by Django 5.0.3 on 2024-11-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_message_iduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('idEx', models.IntegerField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('organisation', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
