# Generated by Django 5.0.3 on 2024-11-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='present',
            field=models.IntegerField(default=True),
        ),
    ]
