# Generated by Django 5.0.3 on 2024-11-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_experience_present'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='idEx',
            new_name='id',
        ),
    ]
