# Generated by Django 5.0.3 on 2024-11-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_idex_experience_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='present',
        ),
        migrations.AlterField(
            model_name='experience',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
