# Generated by Django 5.0.3 on 2024-11-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_experience_present_alter_experience_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
