# Generated by Django 5.0.3 on 2024-11-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_experience_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_year',
            field=models.DateField(default='2024/11/12'),
        ),
    ]
