# Generated by Django 5.0.3 on 2024-11-12 18:29

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_experience_end_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='present',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Yes'), (2, 'No')], default='Yes', max_length=3),
        ),
    ]
